tools:
    php_sim: true
    php_pdepend: true
    php_analyzer:
        enabled: true
        config:
            use_statement_fixes:
                preserve_blanklines:  true

filter:
    excluded_paths:
        - 'vendor/*'
        - 'tests/*'

checks:
    php: true

coding_style:
    php:
        spaces:
            before_keywords:
                catch: false
